zookeeper:
  image: confluent/zookeeper:latest
  ports:
    - "2181:2181"

kafka:
  image: confluent/kafka:latest
  links:
    - zookeeper
  ports:
    - "9092:9092"
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103

schemaregistry:
  image: confluent/schema-registry:latest
  links:
    - zookeeper
    - kafka
  ports:
    - "8081:8081"

postgres:
  build: ./postgres
  ports:
    - "5432:5432"

elasticsearch:
  image: elasticsearch:2.1.0
  ports:
    - "9200:9200"
    - "9300:9300"
  command: -Des.network.host=0.0.0.0 #otherwise it binds to 127.0.0.1 and isn't accessible outside boot2docker

grafana:
  image: cazcade/docker-grafana-graphite:latest
  ports:
    - "8123:80"
    - "2003:2003"
